### ISSUE TITLE
Hi,Could you teach me how to calibrate the imu with the lidar

### ISSUE THREAD

**Issue by AdamPengG** [zxl19/Hand_Eye_Extrinsic_Calibration#2]
Hi, Zxl19. I have try use the tool to get the imu.dat . But there is no function for calibrate the imu with lidar. Could you tell me how to use this program to calibrate the imu and lidar.

**Comment by zxl19** [comment]
Hi @AdamPengG ! In our case we used an inertial navigation system (GNSS+IMU) to estimate 6 DoF pose. If you can estimate IMU pose and output in [this format](https://github.com/zxl19/Hand_Eye_Extrinsic_Calibration#2-input-pose-format), then you can config and run `main_calibration_L2I_quat_interp.m ` to see the results. You can refer to [this README file](https://github.com/zxl19/Hand_Eye_Extrinsic_Calibration/tree/main/tools) to prepare your data.

Best wishes.

**Comment by AdamPengG** [comment]
Thanks Z. Could I put the ros imu message's quaternion to replace the INS' quaternion.

**Comment by zxl19** [comment]
Sure you can. But you may need to estimate the translation part of the pose by IMU integration.

**Comment by AdamPengG** [comment]
I got it. Thank you for your generous.
