### ISSUE TITLE
A little confuse about the lidar coordinate system and odomtery coordinate system

### ISSUE THREAD

**Issue by AdamPengG** [zxl19/Hand_Eye_Extrinsic_Calibration#3]
Hi Zhang, thanks for your previously generous help. I have confuse about the lidar coordinate system and odomtery coordinate system. My lidar coordinate system is x(back),y(left),z(up). Is the topic, /aft_mapped_to_init, coordinate system is the same  x(back),y(left),z(up)?
Emm, take a example, I assume your lidar corrdinate system is x(front),y(right),z(up) and my lidar coordinate system is x(back),y(left),z(up) 。After the process of loam,we get same odomtery /aft_mapped_to_init. I put the Lidar odomtery CSV and INS CSV. The matlab will give a transformation matrix base on my lidar coordinate system ,x(back),y(left),z(up), right？

**Comment by zxl19** [comment]
Yes, you are right. The LiDAR coordinate system is essentially the same as odometry coordinate system. Because the points in a LiDAR scan is in the LiDAR coordinate system. And LiDAR odometry estimates the poses of LiDAR coordinate system based on the input points. However in certain algorithms (e.g. LeGO-LOAM) they are not the same because the input points are transformed before pose estimation.

**Comment by AdamPengG** [comment]
You mean that ,in the lego-loam, there is a rotation between LIDAR coordinate system and LIDAR Odometry  coordinate system. 
If I used lego-loam to output the odometry,  the transformation matrix from matlab shows relation between LIDAR Odomety and INS . Then I want to get the transformation between Lidar and INS,  I should use Matlab transformation matrix * Lego-loam Lidar&Lidar Odometry's rotation matrix. 
However, A-LOAM will directly output the transfromation between the Lidar and INS.

**Comment by zxl19** [comment]
LeGO-LOAM transformed the point cloud during the process:

```cpp
point.x = segmentedCloud->points[i].y;
point.y = segmentedCloud->points[i].z;
point.z = segmentedCloud->points[i].x;
```

You can refer to [featureAssociation.cpp#L500](https://github.com/RobustFieldAutonomyLab/LeGO-LOAM/blob/896a7a95a8bc510b76819d4cc48707e344bad621/LeGO-LOAM/src/featureAssociation.cpp#L500) for more details.

**Comment by AdamPengG** [comment]
It works. Thank you very much ,Zhang.
