### ISSUE TITLE
About Z-axis drift

### ISSUE THREAD

**Issue by AdamPengG** [zxl19/Hand_Eye_Extrinsic_Calibration#5]
张同学你好，
我自己使用lego-loam录制了轨迹，用来和INS进行配准。发现旋转heading,pitch,roll和XY的平移误差都比较小，我计算的是旋转平移后同时刻点的pose误差，XY坐标平均误差偏移在5cm以内，但是Z轴的偏移比较高，平均误差大约是25cm左右，请问你也有遇到过这样的问题吗？

**Comment by zxl19** [comment]
@AdamPengG 您好！问题来源可能有两方面，一是LeGO-LOAM的位姿估计结果在Z方向上误差较大，这是激光里程计普遍存在的问题，但是在标定场景这种小范围场景下误差通常可以接受；二是由于激光雷达和INS的Z坐标轴方向基本上重合，车辆在在运动中近似平面运动，垂直方向位姿增量不明显，导致手眼标定获得的垂直方向的外参不准确，我在自己测试中获得的垂向外参通常在-1m（规定的优化变量的下限处），可以将垂直方向的外参替换为测量值，或者采用激光雷达-相机-INS联合标定获得更好的外参标定结果。

**Comment by AdamPengG** [comment]
感谢！您的意思，是可以通过物理测量（卷尺，激光水平仪等）INS和Lidar的Z轴平移变量。然后用物理测量的Z轴偏移量，去替换程序计算出来的平移矩阵中的Z方向的偏移，旋转和XY的偏移还是依照计算出结果。

**Comment by zxl19** [comment]
@AdamPengG 是的，您可以先这样尝试一下，看这组外参是否满足应用要求。垂向外参的误差会对定位和建图的绝对高度（海拔高度）有影响，如果只关注相对高度（某位置相对于某位置高多少）的话垂向外参存在一些误差应该是可以接受的，甚至有些算法中只要求确定车辆的`x y yaw`三个自由度位姿（地面车辆毕竟不会飞）。

**Comment by AdamPengG** [comment]
了解，感谢。还有一个问题，关于下面的代码：
`lb = [-1, -1, -1, -2, -2, -2, -2];
ub = [1, 1, 1, 2, 2, 2, -2];
x0 = (lb + ub)/2; % x y z (m) qw qx qy qz`
最后一个qz的上边界和下边界为什么都是-2呢？我修改为2之后，发现结果并没有改变，只是迭代周期增加了。

**Comment by zxl19** [comment]
@AdamPengG 这里应该是我的笔误，您是在哪个文件中发现的，我检查一下。

**Comment by AdamPengG** [comment]
在 [Hand_Eye_Extrinsic_Calibration/main_calibration_L2I_quat_interp.m ](https://github.com/zxl19/Hand_Eye_Extrinsic_Calibration/blob/e785fa2c82bbd88b401ae6f1890685ab4c9064bf/main_calibration_L2I_quat_interp.m#L76-L78)中发现的。

**Comment by zxl19** [comment]
@AdamPengG `qz`的上限应该改为2，这里是我的笔误。

**Comment by AdamPengG** [comment]
感谢您慷慨的解答。

**Comment by zxl19** [comment]
不客气。

**Comment by AdamPengG** [comment]
能方便加您个微信吗？方便以后交流。My wechat:424158674
