### ISSUE TITLE
Lidar-GNSS Calibration

### ISSUE THREAD

**Issue by TheTomer** [zxl19/Hand_Eye_Extrinsic_Calibration#6]
Hi @zxl19 , I'd like to use your code to perform a Lidar to GNSS/INS alignment, but I'm not sure how to translate my data to fit the desired input. 

For the Lidar - I have point clouds with a timestamp, x,y,z coordinates and intensity for each point.
For the GNSS - I have a whole lot of information, which also contains latitude, longitude, elevation, angle (headings, pitch, roll), etc.

How can I convert that data to the format your code requires?

**Comment by zxl19** [comment]
Hi @TheTomer , you can refer to the [Input Pose Format](https://github.com/zxl19/Hand_Eye_Extrinsic_Calibration#2-input-pose-format) section in README.md for more details. Basically you need a LiDAR SLAM algorithm to estimate LiDAR poses and convert LiDAR and GNSS poses into required format before using this repository for calibration. If you encounter further problems, please let me know.

Best regards.

**Comment by TheTomer** [comment]
Thanks for your quick reply @zxl19 , could you please clarify what qw qx qy qz mean?

**Comment by zxl19** [comment]
Hi @TheTomer , `qw qx qy qz` is a [quaternion](https://en.wikipedia.org/wiki/Quaternion) representing rotation. 

$\boldsymbol{q} = q_{w} + q_{x}\boldsymbol{i} + q_{y}\boldsymbol{j} + q_{z}\boldsymbol{k}$
